name: pr_to_main

on:
  pull_request:
    branches:
      - main
env:
  DBT_PROFILES_DIR: ./

  DBT_GOOGLE_PROJECT_DEV: ${{ secrets.DBT_GOOGLE_PROJECT_DEV }}
  DBT_GOOGLE_BIGQUERY_DATASET_DEV: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET_DEV }}
  # The DBT_GOOGLE_BIGQUERY_KEYFILE_DEV secret will be written to a json file below
  DBT_GOOGLE_BIGQUERY_KEYFILE_DEV: ./dbt-service-account.json

jobs:
  pr_to_main:
    name: pr_to_main
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE_DEV}}

      - name: Install dependencies
        run: |
          pip install dbt-bigquery
          dbt deps
          ls

      # Add dbt seed or other commands here if needed
#
#      - name: Run dbt models
#        run: dbt debug
#
#      - name: Run dbt models
#        run: dbt run
#
#      - name: Test dbt models
#        run: dbt test

      - name: build single html
        run: |
          dbt docs generate
          python dbt-docs-spa.py
#      - name: deploy docs
#        uses: ./
#        with:
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          remote_url: https://github.com/dbt-cloud/gh-pages-action.git

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.PASSWORD }}